- name: adicionando repositorio
  command: add-apt-repository "https://download.docker.com/linux/ubuntu "{{ ansible_distribution_release }}" stable"
  when: ansible_hostname == "docker"

#- name: adicionando repositorio 4linux
#  apt_repository:
#   repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu "{{ ansible_distribution_release }}" stable
#   state: present


- name: atualizando repositorio
  command: apt-get update
  when: ansible_hostname == "docker"
