- name: instalando pacotes no SO
  hosts: all
  tasks:
   - name: instalando pacotes p debian
     apt:
      name: "{{ item }}"
      state: present
     with_items:
      - vim
      - nano
      - sl
     when: ansible_os_family == "RedHat"
